name: az_base
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flustars: ^2.0.1 #工具类 https://pub.flutter-io.cn/packages/flustars
  fluttertoast: ^8.0.8  #提示  https://pub.flutter-io.cn/packages/fluttertoast
  day: ^0.7.1 #时间处理  https://pub.flutter-io.cn/packages/day
  flutter_svg: 0.22.0  #svg  https://pub.flutter-io.cn/packages/flutter_svg/install
  dio: ^4.0.0 #网络s请求  https://pub.flutter-io.cn/packages/dio
  cached_network_image: ^3.2.0   #图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  get: ^4.6.1 #getx状态管理
  fluro: ^2.0.3 #路由
  flutter_screenutil: 5.0.1 #屏幕适配 https://pub.flutter-io.cn/packages/flutter_screenutil/install
  flutter_openim_widget: #IMUI组件 https://github.com/Poker-J/flutter_openim_widget.git
    git:
      url: git@github.com:Poker-J/flutter_openim_widget.git
      ref: im2.0
  flutter_swiper_tv: ^1.1.6-nullsafety
  flutter_html: any #富文本
  better_player: ^0.0.73 #视频播放器
  photo_view: ^0.13.0 #图片预览
  flutter_easyrefresh: ^2.2.1 #下拉刷新
  connectivity_plus: ^2.0.2 #手机网络连接状态
  dio_http_cache: ^0.3.0 #接口缓存 https://pub.flutter-io.cn/packages/dio_http_cache/install

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  xml_parser: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.azbase.az_base
        pluginClass: AzBasePlugin
      ios:
        pluginClass: AzBasePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
